Repository brstu/GIIS-2024, pull requests merged in 2024-04, with the labels that each got.

#25 [task_01] Add Task 01
  README.md
  trunk/ii02216/task_01/doc/1.jpg
  trunk/ii02216/task_01/doc/10.jpg
  trunk/ii02216/task_01/doc/11.jpg
  trunk/ii02216/task_01/doc/2.jpg
  trunk/ii02216/task_01/doc/3.jpg
  trunk/ii02216/task_01/doc/4.jpg
  trunk/ii02216/task_01/doc/5.jpg
  trunk/ii02216/task_01/doc/6.jpg
  trunk/ii02216/task_01/doc/7.jpg
  trunk/ii02216/task_01/doc/8.jpg
  trunk/ii02216/task_01/doc/9.jpg
  trunk/ii02216/task_01/readme.md
  trunk/ii02216/task_01/src/assets/Tanjiro.jpg
  trunk/ii02216/task_01/src/assets/Tomioka.jpg
  trunk/ii02216/task_01/src/main.py
  trunk/ii02216/task_01/src/requirements.txt
Labels: python

#34 [task_03] Add Task3
  README.md
  trunk/ii02205/task_01/images/result1.jpg
  trunk/ii02205/task_01/images/result2.jpg
  trunk/ii02205/task_01/images/result3.jpg
  trunk/ii02205/task_01/images/source.jpg
  trunk/ii02205/task_01/readme.md
  trunk/ii02205/task_01/src/main.py
  trunk/ii02205/task_01/src/requirements.txt
  trunk/ii02205/task_01/src/result.jpg
  trunk/ii02205/task_01/src/source.jpg
  trunk/ii02205/task_02/images/image1.png
  trunk/ii02205/task_02/images/image2.png
  trunk/ii02205/task_02/images/image3.png
  trunk/ii02205/task_02/readme.md
  trunk/ii02205/task_02/src/adress_book.py
  trunk/ii02205/task_02/src/main.py
  trunk/ii02205/task_02/src/requirements.txt
  trunk/ii02205/task_02/src/window.py
  trunk/ii02205/task_03/images/image1.png
  trunk/ii02205/task_03/images/image2.png
  trunk/ii02205/task_03/images/image3.png
  trunk/ii02205/task_03/readme.md
  trunk/ii02205/task_03/src/api_service.dart
  trunk/ii02205/task_03/src/exit_page.dart
  trunk/ii02205/task_03/src/friends_page.dart
  trunk/ii02205/task_03/src/home_page.dart
  trunk/ii02205/task_03/src/main.dart
  trunk/ii02205/task_03/src/messages_page.dart
  trunk/ii02205/task_03/src/pubspec.yaml
Labels: question

#41 [task_04] Add task 4-5
  README.md
  trunk/ii02205/task_04/images/image1.png
  trunk/ii02205/task_04/images/image2.png
  trunk/ii02205/task_04/images/image3.png
  trunk/ii02205/task_04/images/invador_1.png
  trunk/ii02205/task_04/images/invador_2.png
  trunk/ii02205/task_04/images/invador_3.png
  trunk/ii02205/task_04/images/invador_4.png
  trunk/ii02205/task_04/images/invador_5.png
  trunk/ii02205/task_04/images/invador_6.png
  trunk/ii02205/task_04/images/player.png
  trunk/ii02205/task_04/images/player1.png
  trunk/ii02205/task_04/readme.md
  trunk/ii02205/task_04/src/application.py
  trunk/ii02205/task_04/src/main.py
  trunk/ii02205/task_04/src/moving.py
  trunk/ii02205/task_04/src/requirements.txt
Labels: python, conflict

#61 [task_02] Add task 2
  README.md
  trunk/ii002203/task_02/images/loadData.png
  trunk/ii002203/task_02/images/removeData.png
  trunk/ii002203/task_02/images/searchData.png
  trunk/ii002203/task_02/images/start.png
  trunk/ii002203/task_02/readme.md
  trunk/ii002203/task_02/src/CMakeLists.txt
  trunk/ii002203/task_02/src/addressbook.cpp
  trunk/ii002203/task_02/src/addressbook.h
  trunk/ii002203/task_02/src/addressbook.ui
  trunk/ii002203/task_02/src/main.cpp
Labels: c/c++
